# Task 05 - Part 1 of 2: SQL Aggregations & GROUP BY

**Course:** Database Applications Development  
**Lesson:** 05 - SQL Aggregations, Grouping, and Excel Export (in Part 2) 

---

## Instructions

Complete all exercises in this notebook. You will:
1. Write SQL queries using aggregate functions
2. Use GROUP BY to analyze categories
3. Export 4 query results to Excel files
4. Answer analysis questions

**Resources:**
- Lesson materials (dbApps05_AggregationsGrouping.md)
- Walkthrough notebook (dbApps05_Walkthrough.ipynb)
- SQL Reference Guide (updated with aggregations)

**Submission:**
1. Complete all TODO sections
2. Verify all cells run without errors
3. Check that Excel files were created (in Part 2)
4. Push to GitHub: `databaseApplications/dbApps05TasksPart1.ipynb`

Let's practice aggregations!

---

## Setup

In [69]:
import pandas as pd
import sqlite3

# Connect to database
conn = sqlite3.connect('nba_5seasons.db')
print("✅ Connected to database")

✅ Connected to database

---

## Part 1: Basic Aggregate Functions (10 queries)

Practice using COUNT, SUM, AVG, MIN, and MAX without GROUP BY.

**Hints:**
- Remember to use AS to name your result columns
- Aggregate functions work on ALL rows that match your WHERE clause
- Use ROUND(AVG(column), 1) to round decimals

### Query 1: Count All Teams

**Task:** How many teams are in the database?

**Hint:** Use COUNT(*) on the teams table.

In [73]:
# TODO: Write your query
query_1 = """
SELECT COUNT(*) AS total_teams
FROM teams
"""

result_1 = pd.read_sql(query_1, conn)
display(result_1)

   total_teams
0           30

### Query 2: Count Player Season Records

**Task:** How many player-season records exist for 2021-22?

**Hint:** COUNT(*) from player_season_stats WHERE season = '2021-22'

In [76]:
# TODO: Write your query
query_2 = """
SELECT COUNT(*) AS total_players
FROM player_season_stats
WHERE season = '2021-22'
"""

result_2 = pd.read_sql(query_2, conn)
display(result_2)

   total_players
0            605

### Query 3: Total Points (All Teams)

**Task:** What were the total combined points scored by all teams in all 2021-22 games?

**Hint:** SUM(pts) from team_game_stats WHERE season = '2021-22'

In [79]:
# TODO: Write your query
query_3 = """
SELECT SUM(pts) AS total_points
FROM team_game_stats
WHERE season = '2021-22'
"""

result_3 = pd.read_sql(query_3, conn)
display(result_3)

   total_points
0        272115

### Query 4: Average Points Per Game (League-Wide)

**Task:** What was the league-wide average points per game in 2021-22?

**Hint:** AVG(pts), remember to round to 1 decimal place

In [82]:
# TODO: Write your query
query_4 = """
SELECT ROUND(AVG(pts), 1) AS avg_pts
FROM team_game_stats
WHERE season = '2021-22'
"""

result_4 = pd.read_sql(query_4, conn)
display(result_4)

   avg_pts
0    110.6

### Query 5: Highest and Lowest Scores

**Task:** Find the highest and lowest points scored in any single game during 2021-22.

**Hint:** Use both MAX(pts) and MIN(pts) in one query

In [85]:
# TODO: Write your query
query_5 = """
SELECT 
MIN(pts) AS min_points,
MAX(pts) AS max_points
FROM team_game_stats
WHERE season = '2021-22'
"""

result_5 = pd.read_sql(query_5, conn)
display(result_5)

   min_points  max_points
0          75         158

### Query 6: Lakers Total Points

**Task:** How many total points did the Lakers (team_id = 1610612747) score in 2021-22?

**Hint:** SUM(pts) with WHERE for team_id AND season

In [88]:
# TODO: Write your query
query_6 = """
SELECT SUM(pts) AS lakers_total_points
FROM team_game_stats
WHERE team_id = 1610612747 AND season = '2021-22'
"""

result_6 = pd.read_sql(query_6, conn)
display(result_6)

   lakers_total_points
0                 9192

### Query 7: Warriors Average Points

**Task:** What was the Warriors' (team_id = 1610612744) average points per game in 2021-22?

**Hint:** AVG(pts), round to 1 decimal

In [91]:
# TODO: Write your query
query_7 = """
SELECT ROUND(AVG(pts), 1) AS avg_points
FROM team_game_stats
WHERE team_id = 1610612744 AND season = '2021-22'
"""

result_7 = pd.read_sql(query_7, conn)
display(result_7)

   avg_points
0       111.0

### Query 8: Complete Summary Statistics

**Task:** Create a summary with COUNT, SUM, AVG, MIN, and MAX for 'pts' for all games in 2021-22.

**Hint:** Use all 5 aggregate functions in one SELECT statement

In [94]:
# TODO: Write your query
query_8 = """
SELECT
COUNT(*) AS games,
SUM(pts) AS total_points,
AVG(pts) AS avg_points,
MIN(pts) AS min_points,
MAX(pts) AS max_points
FROM team_game_stats
WHERE season = '2021-22';
"""

result_8 = pd.read_sql(query_8, conn)
display(result_8)

   games  total_points  avg_points  min_points  max_points
0   2460        272115  110.615854          75         158

### Query 9: Count Teams by State

**Task:** How many teams are located in California?

**Hint:** COUNT(*) from teams WHERE state = 'California'

In [97]:
# TODO: Write your query
query_9 = """
SELECT COUNT(*)
FROM teams
WHERE state = "California"
"""

result_9 = pd.read_sql(query_9, conn)
display(result_9)

   COUNT(*)
0         4

### Query 10: Oldest Team

**Task:** What is the earliest year_founded in the teams table?

**Hint:** MIN(year_founded)

In [100]:
# TODO: Write your query
query_10 = """

SELECT MIN(year_founded) AS oldest_year_founded
FROM teams
"""

result_10 = pd.read_sql(query_10, conn)
display(result_10)

   oldest_year_founded
0                 1946

---

## Part 2: GROUP BY Queries (8 queries)

Practice grouping data and aggregating by category.

**Remember:**
- Every non-aggregated column in SELECT must be in GROUP BY
- GROUP BY creates separate groups for aggregation
- Use ORDER BY to sort your results

### Query 11: Games Per Team

**Task:** How many games did each team play in 2021-22?

**Hint:** SELECT team_id, COUNT(*) ... GROUP BY team_id

In [104]:
# TODO: Write your query
query_11 = """

SELECT team_id, COUNT(*) AS games_played
FROM team_game_stats
WHERE season = '2021-22'
GROUP BY team_id
ORDER BY games_played DESC
"""

result_11 = pd.read_sql(query_11, conn)
display(result_11.head(10))  # Show first 10 teams

      team_id  games_played
0  1610612766            82
1  1610612765            82
2  1610612764            82
3  1610612763            82
4  1610612762            82
5  1610612761            82
6  1610612760            82
7  1610612759            82
8  1610612758            82
9  1610612757            82

### Query 12: Average Points By Team

**Task:** Calculate average points per game for each team in 2021-22. Sort by highest average first.

**Hint:** GROUP BY team_id, ORDER BY avg_points DESC

In [107]:
# TODO: Write your query
query_12 = """

SELECT team_id, ROUND(AVG(pts), 1) AS avg_points
FROM team_game_stats
WHERE season = '2021-22'
GROUP BY team_id
ORDER BY avg_points DESC
"""

result_12 = pd.read_sql(query_12, conn)
display(result_12.head(10))  # Show first 10 teams

      team_id  avg_points
0  1610612750       115.9
1  1610612763       115.6
2  1610612749       115.5
3  1610612766       115.3
4  1610612756       114.8
5  1610612737       113.9
6  1610612762       113.6
7  1610612759       113.2
8  1610612751       112.9
9  1610612743       112.7

### Query 13: Team Performance with Names

**Task:** Show team name, games played, and average points for each team in 2021-22.

**Hint:** JOIN teams with team_game_stats, then GROUP BY

In [110]:
# TODO: Write your query
query_13 = """

SELECT t.full_name AS team_name,
       COUNT(*) AS games_played,
       ROUND(AVG(g.pts), 1) AS avg_points
FROM team_game_stats g
JOIN teams t ON g.team_id = t.team_id
WHERE g.season = '2021-22'
GROUP BY t.team_id, t.full_name
ORDER BY avg_points DESC
"""

result_13 = pd.read_sql(query_13, conn)
display(result_13.head(10))

                team_name  games_played  avg_points
0  Minnesota Timberwolves            82       115.9
1       Memphis Grizzlies            82       115.6
2         Milwaukee Bucks            82       115.5
3       Charlotte Hornets            82       115.3
4            Phoenix Suns            82       114.8
5           Atlanta Hawks            82       113.9
6               Utah Jazz            82       113.6
7       San Antonio Spurs            82       113.2
8           Brooklyn Nets            82       112.9
9          Denver Nuggets            82       112.7

### Query 14: Total Points By Team

**Task:** Calculate total points scored by each team in 2021-22. Include team name.

**Hint:** SUM(pts), JOIN with teams table, GROUP BY team

In [113]:
# TODO: Write your query
query_14 = """

SELECT t.full_name AS team_name,
       SUM(g.pts) AS total_points
FROM team_game_stats g
JOIN teams t ON g.team_id = t.team_id
WHERE g.season = '2021-22'
GROUP BY t.team_id, t.full_name
ORDER BY total_points DESC
"""

result_14 = pd.read_sql(query_14, conn)
display(result_14.head(10))

                team_name  total_points
0  Minnesota Timberwolves          9507
1       Memphis Grizzlies          9480
2         Milwaukee Bucks          9470
3       Charlotte Hornets          9457
4            Phoenix Suns          9416
5           Atlanta Hawks          9343
6               Utah Jazz          9316
7       San Antonio Spurs          9279
8           Brooklyn Nets          9258
9          Denver Nuggets          9243

### Query 15: Season High by Team

**Task:** Find each team's highest-scoring game in 2021-22. Include team name and sort by highest game.

**Hint:** MAX(pts), JOIN, GROUP BY, ORDER BY DESC

In [116]:
# TODO: Write your query
query_15 = """

SELECT t.full_name AS team_name,
       MAX(g.pts) AS season_high_points
FROM team_game_stats g
JOIN teams t ON g.team_id = t.team_id
WHERE g.season = '2021-22'
GROUP BY t.team_id, t.full_name
ORDER BY season_high_points DESC
"""

result_15 = pd.read_sql(query_15, conn)
display(result_15.head(10))

                team_name  season_high_points
0       Charlotte Hornets                 158
1       San Antonio Spurs                 157
2    Los Angeles Clippers                 153
3      Washington Wizards                 153
4       Memphis Grizzlies                 152
5           Brooklyn Nets                 150
6  Minnesota Timberwolves                 149
7         Houston Rockets                 146
8      Los Angeles Lakers                 146
9          Boston Celtics                 145

### Query 16: Win Count by Team

**Task:** Count how many wins each team had in 2021-22.

**Hint:** Use SUM(CASE WHEN wl = 'W' THEN 1 ELSE 0 END) to count wins

In [119]:
# TODO: Write your query
query_16 = """

SELECT t.full_name AS team_name,
       SUM(CASE WHEN g.wl = 'W' THEN 1 ELSE 0 END) AS wins
FROM team_game_stats g
JOIN teams t ON g.team_id = t.team_id
WHERE g.season = '2021-22'
GROUP BY t.team_id, t.full_name
ORDER BY wins DESC
"""

result_16 = pd.read_sql(query_16, conn)
display(result_16.head(10))

               team_name  wins
0           Phoenix Suns    64
1      Memphis Grizzlies    56
2  Golden State Warriors    53
3             Miami Heat    53
4       Dallas Mavericks    52
5         Boston Celtics    51
6        Milwaukee Bucks    51
7     Philadelphia 76ers    51
8              Utah Jazz    49
9         Denver Nuggets    48

### Query 17: Teams by State

**Task:** Count how many teams are in each state.

**Hint:** GROUP BY state from teams table

In [122]:
# TODO: Write your query
query_17 = """

SELECT state, COUNT(*) AS team_count
FROM teams
GROUP BY state
ORDER BY team_count DESC, state
"""

result_17 = pd.read_sql(query_17, conn)
display(result_17.head(10))

                  state  team_count
0            California           4
1                 Texas           3
2               Florida           2
3              New York           2
4               Arizona           1
5              Colorado           1
6  District of Columbia           1
7               Georgia           1
8              Illinois           1
9               Indiana           1

### Query 18: Players Per Team

**Task:** Count how many player-season records each team has for 2021-22.

**Hint:** COUNT(*) from player_season_stats, GROUP BY team_id

In [125]:
# TODO: Write your query
query_18 = """

SELECT team_id, COUNT(*) AS player_season_records
FROM player_season_stats
WHERE season = '2021-22'
GROUP BY team_id
ORDER BY player_season_records DESC
"""

result_18 = pd.read_sql(query_18, conn)
display(result_18.head(10))

      team_id  player_season_records
0  1610612760                     26
1  1610612765                     25
2  1610612757                     24
3  1610612764                     23
4  1610612763                     22
5  1610612756                     22
6  1610612739                     22
7  1610612738                     22
8  1610612753                     21
9  1610612752                     21